site_name: DigitalActuary.co.uk
nav:
    - Home: index.md
    - Rationale: pythonic-heavy-modelling.md
    - Getting Started:
       - Installation: installation.md
       - Walkthrough: model-walkthrough.md
       - Definitions: definitions.md
       - Project Layout: project-layout.md
    - Use Cases:
       - Stochastic Modelling: stochastic-modelling.md
       - Asset Modelling: asset-modelling.md
    - Utilities:
       - Typed CSV: typed-csv-specification.md
theme:
    name: journal

copyright: (c)2020 Lewis Fogden
